### ISSUE TITLE
'Admin' panel voor uploaden, beheren en beoordelen (docent/slb) materialen.

### ISSUE THREAD

**Issue by WouterBrookhuis** [JannickZeegers/INF1G-Project-Online-Portfolio#2]
Belangrijk om te hebben.
- Gebruiker moet inloggen
- Als student, dan mogelijkheid eigen materialen te uploaden / aan te passen
- Als slb/docent, dan mogelijkheid een lijst met materialen te zien en te beoordelen
  (Al beoordeelde materialen alleen aan te passen door de oorspronkelijke beoordelaar!)
- Als admin, lijst gebruikers, materialen, cijfers, vakken. Alles aan te passen!
- Meer? Comment below!

**Comment by daanhaitsma** [comment]
Nog steeds bezig, @WouterBrookhuis?

**Comment by WouterBrookhuis** [comment]
Natuurlijk, moet de laatste dingen voor de 2017 release nog even afronden.
